- name: Mettre à jour tous les paquets
  dnf:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"

- name: Installer git
  dnf:
    name: git
    state: present
  when: ansible_os_family == "RedHat"

- name: Ajouter le dépôt NodeSource
  shell: curl -fsSL https://rpm.nodesource.com/setup_23.x | bash -
  when: ansible_os_family == "RedHat"

- name: Installer Node.js
  dnf:
    name: nodejs
    state: present
  when: ansible_os_family == "RedHat"

- name: Cloner le dépôt quiz-ansible
  git:
    repo: https://github.com/franklin-tutorials/quiz-ansible.git
    dest: /opt/quiz-ansible
    version: main
    force: true
  when: ansible_os_family == "RedHat"

- name: Installer les dépendances Node.js
  npm:
    path: /opt/quiz-ansible
    production: no
  when: ansible_os_family == "RedHat"

- name: Construire l'application
  shell: npm run build
  args:
    chdir: /opt/quiz-ansible
  when: ansible_os_family == "RedHat"

- name: Installer serve en global
  npm:
    name: serve
    global: true
  when: ansible_os_family == "RedHat"

- name: Lancer l'application (serve)
  shell: nohup serve -s dist &
  args:
    chdir: /opt/quiz-ansible
  when: ansible_os_family == "RedHat"
