- name: Installer les dépendances système sur Debian/Ubuntu
  apt:
    name:
      - git
      - curl
    state: present
    update_cache: yes
  when: ansible_os_family in ["Debian","Ubuntu"]

- name: Installer les dépendances système sur RedHat/Rocky
  dnf:
    name:
      - git
      - curl
    state: present
  when: ansible_os_family == "RedHat"

- name: Ajouter le dépôt NodeSource (Debian/Ubuntu)
  shell: curl -fsSL https://deb.nodesource.com/setup_23.x | bash -
  args:
    warn: false
  when: ansible_os_family in ["Debian","Ubuntu"]

- name: Installer Node.js sur Debian/Ubuntu
  apt:
    name: nodejs
    state: present
  when: ansible_os_family == "Ubuntu"

- name: Ajouter le dépôt NodeSource (RedHat/Rocky)
  shell: curl -fsSL https://rpm.nodesource.com/setup_23.x | bash -
  args:
    warn: false
  when: ansible_os_family == "RedHat"

- name: Installer Node.js sur RedHat/Rocky
  yum:
    name: nodejs
    state: present
  when: ansible_os_family == "RedHat"

- name: Cloner le dépôt quiz-ansible
  git:
    repo: https://github.com/franklin-tutorials/quiz-ansible.git
    dest: /opt/quiz-ansible
    version: master

- name: Installer les dépendances Node.js
  npm:
    path: /opt/quiz-ansible
    production: no

- name: Construire l’application
  shell: npm run build
  args:
    chdir: /opt/quiz-ansible

- name: Installer serve en global
  npm:
    name: serve
    global: yes

- name: Lancer l’application (serve)
  shell: nohup serve -s dist &
  args:
    chdir: /opt/quiz-ansible
